language: c
sudo: true

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libglew-dev

before_install:
    - sudo apt-add-repository -y ppa:team-xbmc/ppa # libsdl2
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl2-dev

script:
    - cmake -E make_directory build
    - cmake -E chdir build cmake -E time cmake ../src
    - cmake -E time cmake --build build --target all --config Debug --clean-first
    - build/FeverLibrary/FeverTest
    - build/projects/app/app
compiler:
    - clang
    - gcc
